# Generated by Django 4.1.7 on 2023-03-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('Director', models.CharField(max_length=100)),
                ('Genre', models.CharField(max_length=100)),
            ],
        ),
    ]
